pages:
 image: node:latest
 stage: deploy
 script:
  - yarn add --progress=false
  - yarn build
  - rm -rf public
  - mkdir public
  - cp -r dist/* public
 artifacts:
  expire_in: 1 day
  paths:
  - public
 only:
  - main